version: '3'
services:
  app:
    build: flask-sqlite3-todo-crud
    volumes:
      - app:/app
    ports:
      - "5000:5000"
  proxy:
    build: nginx
    restart: always
    ports:
      - 81:81
    depends_on:
      - app
volumes:
  app: