name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:

  build:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t flask-sqlite-todo-crud:latest flask-sqlite3-todo-crud
          docker build -t nginx-todo-crud:latest nginx-todo-crud
      - name: Push Docker image
        run: |
          docker tag flask-sqlite-todo-crud:latest ${{ env.DOCKER_USERNAME }}/flask-sqlite-todo-crud:latest
          docker push ${{ env.DOCKER_USERNAME }}/flask-sqlite-todo-crud:latest
          docker tag nginx-todo-crud:latest ${{ env.DOCKER_USERNAME }}/nginx-todo-crud:latest
          docker push ${{ env.DOCKER_USERNAME }}/nginx-todo-crud:latest
          
          docker tag flask-sqlite-todo-crud:latest ${{ env.DOCKER_USERNAME }}/flask-sqlite-todo-crud:$(date +%s)
          docker push ${{ env.DOCKER_USERNAME }}/flask-sqlite-todo-crud:$(date +%s)
          docker tag nginx-todo-crud:latest ${{ env.DOCKER_USERNAME }}/nginx-todo-crud:
          docker push ${{ env.DOCKER_USERNAME }}/nginx-todo-crud:$(date +%s)
