name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t sre-hw17_app:latest flask-sqlite3-todo-crud
          docker build -t sre-hw17_proxy:latest nginx-todo-crud
      - name: Push Docker image
        run: |
          docker tag sre-hw17_app:latest ${{ env.DOCKER_USERNAME }}/sre-hw17_app:latest
          docker push ${{ env.DOCKER_USERNAME }}/sre-hw17_app:latest
          docker tag sre-hw17_proxy:latest ${{ env.DOCKER_USERNAME }}/sre-hw17_proxy:latest
          docker push ${{ env.DOCKER_USERNAME }}/sre-hw17_proxy:latest
          
          docker tag sre-hw17_app:latest ${{ env.DOCKER_USERNAME }}/sre-hw17_app:$(date +%s)
          docker push ${{ env.DOCKER_USERNAME }}/sre-hw17_app:$(date +%s)
          docker tag sre-hw17_proxy:latest ${{ env.DOCKER_USERNAME }}/sre-hw17_proxy:
          docker push ${{ env.DOCKER_USERNAME }}/sre-hw17_proxy:$(date +%s)
